-- ╔══════════════════════════════════════╗
-- ║         GENERAL CONFIGURATION        ║
-- ╚══════════════════════════════════════╝

hl.config({
    autogenerated = false,

    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        resize_on_border = true,
    },

    decoration = {
        rounding = 10,
        blur = {
            enabled = true,
            size = 8,
            passes = 2,
        },
        shadow = {
            enabled = true,
            range = 20,
            render_power = 3,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        force_split                  = 0,       -- 0: sigue el mouse, 1: siempre izq/arriba, 2: siempre der/abajo
        preserve_split               = true,    -- mantiene el split fijo aunque cambien ventanas
        smart_split                  = true,    -- split preciso según posición del cursor
        smart_resizing               = true,    -- redimensiona desde la esquina más cercana al cursor
        permanent_direction_override = false,
        special_scale_factor         = 1,
        split_width_multiplier       = 1.0,
        use_active_for_splits        = true,
        default_split_ratio          = 1.0,     -- 1.0 = 50/50 al abrir ventana
        split_bias                   = 0,
        precise_mouse_move           = true,    -- drag más preciso según posición del mouse
    },

    input = {
        kb_layout = "us",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
        },
    },

    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,

      --  vfr = false, 
      --  render_ahead_of_time = false,
       -- force_default_wallpaper = 0,
    },

})